name: Publish Latest Version

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: macos-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.SHINED_NPM_PUBLISH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.event.release.tag_name}}

      - name: Use Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ vars.PNPM_7_VERSION }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Testing
        run: pnpm run test:cov

      - name: Building
        run: pnpm build

      - name: Publich Release Package
        run: pnpm publish --access public --tag latest --no-git-checks
